services:
  - type: web
    name: powerbi-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: DATABASE_URL
        value: postgresql://powerbi_db_user:hMYdgQKbZykj5d49nbreMJRI9L2Rxu4W@dpg-d0vo7jali9vc73d3arj0-a/powerbi_db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
